apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: security-service-hpa
  namespace: khi
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: security-service-depl
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
