apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: totp-service-hpa
  namespace: service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: totp-service-depl
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
