apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway-service-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigateway-service-depl
  template:
    metadata:
      labels:
        app: apigateway-service-depl
    spec:
      containers:
        - name: apigateway-container
          image: apigateway-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "1"
              memory: "500Mi"
            requests:
              cpu: "0.5"
              memory: "250Mi"
          env:
            - name: SPRING_DATA_REDIS_SENTINEL_MASTER
              value: "mymaster"
            - name: SPRING_DATA_REDIS_SENTINEL_NODES
              value: "redis-sentinel:26379"
            - name: JWT-SECRET
              valueFrom:
                secretKeyRef:
                  name: omnimfa-secret
                  key: JWT-SECRET
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: apigateway-k8ssvc
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: apigateway-service-depl
