apiVersion: apps/v1
kind: Deployment
metadata:
  name: onboarding-service-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onboarding-service-depl
  template:
    metadata:
      labels:
        app: onboarding-service-depl
    spec:
      containers:
        - name: onboarding-container
          image: onboarding-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
            - containerPort: 9090
          resources:
            limits:
              cpu: "1"
              memory: "500Mi"
            requests:
              cpu: "0.5"
              memory: "250Mi"
          env:
            - name: SPRING_DATA_REDIS_SENTINEL_MASTER
              value: "mymaster"
            - name: SPRING_DATA_REDIS_SENTINEL_NODES
              value: "redis:26379"
            - name: SPRING_DATA_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: omnimfa-secret
                  key: REDIS-PASSWORD
            - name: DATASOURCE-URL
              value: "jdbc:mysql://mysql-k8ssvc:3306/onboarding?useSSL=false"
            - name: DATASOURCE-USERNAME
              value: "root"
            - name: DATASOURCE-PASSWORD
              valueFrom:
                secretKeyRef:
                  name: omnimfa-secret
                  key: MYSQL-PASSWORD
            - name: JWT-SECRET
              valueFrom:
                secretKeyRef:
                  name: omnimfa-secret
                  key: JWT-SECRET
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: onboarding-k8ssvc
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: grpc
      port: 9090
      targetPort: 9090
  selector:
    app: onboarding-service-depl
