apiVersion: apps/v1
kind: Deployment
metadata:
  name: totp-service-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: totp-service-depl
  template:
    metadata:
      labels:
        app: totp-service-depl
    spec:
      containers:
        - name: totp-container
          image: totp-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "1"
              memory: "500Mi"
            requests:
              cpu: "0.5"
              memory: "250Mi"
          env:
            - name: DATASOURCE-URL
              value: "jdbc:mysql://mysql:3306/totp?useSSL=false"
            - name: DATASOURCE-USERNAME
              value: "root"
            - name: DATASOURCE-PASSWORD
              valueFrom:
                secretKeyRef:
                  name: omnimfa-secret
                  key: MYSQL-PASSWORD
            - name: JWT-SECRET
              valueFrom:
                secretKeyRef:
                  name: omnimfa-secret
                  key: JWT-SECRET
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: totp-k8ssvc
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: totp-service-depl
